#! /usr/bin/env sh

TRANSLATE_LANG="ar"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="zh"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="fr"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="de"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="it"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="ja"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="pt"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="ru"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"
TRANSLATE_LANG="es"
cat README.md | ./anon-translate > "README_$TRANSLATE_LANG.md"